### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/docker-utilities#2]
there is already a `true` dockerfile: https://hub.docker.com/r/tianon/true/

ping @ChrisAubuchon

**Comment by ChrisAubuchon** [comment]
This was created because there was an issue with `tianon/true` not having a `/tmp` directory and failing underneath our docker images. I don't see a reason to delete the repo.

**Comment by langston-barrett** [comment]
@ChrisAubuchon Sounds good thanks for clarifying!
